







	



.build/mega2560/OneWire/OneWire.d : lib/OneWire/OneWire.cpp
	@mkdir -p .build/mega2560/OneWire
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -Ilib/DallasTemperature -Ilib/OneWire  -MM $^ > $@
	
	@printf ".build/mega2560/OneWire/OneWire.d .build/mega2560/OneWire/" | cat - $@ > $@~ && mv $@~ $@



.build/mega2560/OneWire/dependencies.d : .build/mega2560/OneWire/OneWire.d
	@echo [96mScanning dependencies of OneWire[0m
	@mkdir -p .build/mega2560/OneWire
	@cat $^ > $@;

all : .build/mega2560/OneWire/dependencies.d
	@true

