







	



.build/mega2560/Wire/utility/twi.d : lib/Wire/utility/twi.c
	@mkdir -p .build/mega2560/Wire/utility
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -Ilib/RTClib -Ilib/SD -Ilib/SD/utility -Ilib/Wire -Ilib/Wire/utility  -MM $^ > $@
	
	@printf ".build/mega2560/Wire/utility/twi.d .build/mega2560/Wire/utility/" | cat - $@ > $@~ && mv $@~ $@

.build/mega2560/Wire/Wire.d : lib/Wire/Wire.cpp
	@mkdir -p .build/mega2560/Wire
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -Ilib/RTClib -Ilib/SD -Ilib/SD/utility -Ilib/Wire -Ilib/Wire/utility  -MM $^ > $@
	
	@printf ".build/mega2560/Wire/Wire.d .build/mega2560/Wire/" | cat - $@ > $@~ && mv $@~ $@



.build/mega2560/Wire/dependencies.d : .build/mega2560/Wire/utility/twi.d .build/mega2560/Wire/Wire.d
	@echo [96mScanning dependencies of Wire[0m
	@mkdir -p .build/mega2560/Wire
	@cat $^ > $@;

all : .build/mega2560/Wire/dependencies.d
	@true

