




.build/mega2560/src/HydroController_beta_from_Billies_code.cpp : src/HydroController_beta_from_Billies_code.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/HydroController_beta_from_Billies_code.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^

.build/mega2560/src/sketch/sketch.cpp : src/sketch/sketch.ino
	@mkdir -p .build/mega2560/src/sketch
	@echo [93msrc/sketch/sketch.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/HydroController_beta_from_Billies_code.cpp .build/mega2560/src/sketch/sketch.cpp
	@true

