




.build/uno/src/SD_Data_Logger_Test.cpp : src/SD_Data_Logger_Test.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/SD_Data_Logger_Test.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/SD_Data_Logger_Test.cpp
	@true

