




.build/uno/src/waterproof_temperature_sensor_via_dallas.cpp : src/waterproof_temperature_sensor_via_dallas.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/waterproof_temperature_sensor_via_dallas.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/waterproof_temperature_sensor_via_dallas.cpp
	@true

