























.build/mega2560/OneWire/OneWire.o : lib/OneWire/OneWire.cpp
	@echo [93mOneWire/OneWire.cpp[0m
	@mkdir -p .build/mega2560/OneWire
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/OneWire/OneWire.cpp
include .build/mega2560/OneWire/OneWire.d



.build/mega2560/OneWire/libOneWire.a : .build/mega2560/OneWire/OneWire.o
	@echo [92mLinking libOneWire.a[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/mega2560/RTClib/RTClib.o : lib/RTClib/RTClib.cpp
	@echo [93mRTClib/RTClib.cpp[0m
	@mkdir -p .build/mega2560/RTClib
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/RTClib/RTClib.cpp
include .build/mega2560/RTClib/RTClib.d



.build/mega2560/RTClib/libRTClib.a : .build/mega2560/RTClib/RTClib.o
	@echo [92mLinking libRTClib.a[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/mega2560/EEPROMEx/EEPROMex.o : lib/EEPROMEx/EEPROMex.cpp
	@echo [93mEEPROMEx/EEPROMex.cpp[0m
	@mkdir -p .build/mega2560/EEPROMEx
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/EEPROMEx/EEPROMex.cpp
include .build/mega2560/EEPROMEx/EEPROMex.d



.build/mega2560/EEPROMEx/libEEPROMEx.a : .build/mega2560/EEPROMEx/EEPROMex.o
	@echo [92mLinking libEEPROMEx.a[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/mega2560/SD/File.o : lib/SD/File.cpp
	@echo [93mSD/File.cpp[0m
	@mkdir -p .build/mega2560/SD
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/SD/File.cpp
include .build/mega2560/SD/File.d

.build/mega2560/SD/SD.o : lib/SD/SD.cpp
	@echo [93mSD/SD.cpp[0m
	@mkdir -p .build/mega2560/SD
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/SD/SD.cpp
include .build/mega2560/SD/SD.d

.build/mega2560/SD/utility/Sd2Card.o : lib/SD/utility/Sd2Card.cpp
	@echo [93mSD/utility/Sd2Card.cpp[0m
	@mkdir -p .build/mega2560/SD/utility
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/SD/utility/Sd2Card.cpp
include .build/mega2560/SD/utility/Sd2Card.d

.build/mega2560/SD/utility/SdFile.o : lib/SD/utility/SdFile.cpp
	@echo [93mSD/utility/SdFile.cpp[0m
	@mkdir -p .build/mega2560/SD/utility
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/SD/utility/SdFile.cpp
include .build/mega2560/SD/utility/SdFile.d

.build/mega2560/SD/utility/SdVolume.o : lib/SD/utility/SdVolume.cpp
	@echo [93mSD/utility/SdVolume.cpp[0m
	@mkdir -p .build/mega2560/SD/utility
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/SD/utility/SdVolume.cpp
include .build/mega2560/SD/utility/SdVolume.d



.build/mega2560/SD/libSD.a : .build/mega2560/SD/File.o .build/mega2560/SD/SD.o .build/mega2560/SD/utility/Sd2Card.o .build/mega2560/SD/utility/SdFile.o .build/mega2560/SD/utility/SdVolume.o
	@echo [92mLinking libSD.a[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/mega2560/DHT/DHT.o : lib/DHT/DHT.cpp
	@echo [93mDHT/DHT.cpp[0m
	@mkdir -p .build/mega2560/DHT
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/DHT/DHT.cpp
include .build/mega2560/DHT/DHT.d



.build/mega2560/DHT/libDHT.a : .build/mega2560/DHT/DHT.o
	@echo [92mLinking libDHT.a[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/mega2560/Wire/utility/twi.o : lib/Wire/utility/twi.c
	@echo [93mWire/utility/twi.c[0m
	@mkdir -p .build/mega2560/Wire/utility
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc   -o $@ -c lib/Wire/utility/twi.c
include .build/mega2560/Wire/utility/twi.d






.build/mega2560/Wire/Wire.o : lib/Wire/Wire.cpp
	@echo [93mWire/Wire.cpp[0m
	@mkdir -p .build/mega2560/Wire
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/Wire/Wire.cpp
include .build/mega2560/Wire/Wire.d



.build/mega2560/Wire/libWire.a : .build/mega2560/Wire/utility/twi.o .build/mega2560/Wire/Wire.o
	@echo [92mLinking libWire.a[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/mega2560/SPI/SPI.o : lib/SPI/SPI.cpp
	@echo [93mSPI/SPI.cpp[0m
	@mkdir -p .build/mega2560/SPI
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/SPI/SPI.cpp
include .build/mega2560/SPI/SPI.d



.build/mega2560/SPI/libSPI.a : .build/mega2560/SPI/SPI.o
	@echo [92mLinking libSPI.a[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/mega2560/arduino/avr-libc/malloc.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc/malloc.c
	@echo [93marduino/avr-libc/malloc.c[0m
	@mkdir -p .build/mega2560/arduino/avr-libc
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc/malloc.c
include .build/mega2560/arduino/avr-libc/malloc.d

.build/mega2560/arduino/avr-libc/realloc.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc/realloc.c
	@echo [93marduino/avr-libc/realloc.c[0m
	@mkdir -p .build/mega2560/arduino/avr-libc
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc/realloc.c
include .build/mega2560/arduino/avr-libc/realloc.d

.build/mega2560/arduino/WInterrupts.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WInterrupts.c
include .build/mega2560/arduino/WInterrupts.d

.build/mega2560/arduino/wiring.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring.c
include .build/mega2560/arduino/wiring.d

.build/mega2560/arduino/wiring_analog.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_analog.c
include .build/mega2560/arduino/wiring_analog.d

.build/mega2560/arduino/wiring_digital.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_digital.c
include .build/mega2560/arduino/wiring_digital.d

.build/mega2560/arduino/wiring_pulse.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/mega2560/arduino/wiring_pulse.d

.build/mega2560/arduino/wiring_shift.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_shift.c
include .build/mega2560/arduino/wiring_shift.d






.build/mega2560/arduino/CDC.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/CDC.cpp
include .build/mega2560/arduino/CDC.d

.build/mega2560/arduino/HardwareSerial.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/mega2560/arduino/HardwareSerial.d

.build/mega2560/arduino/HID.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/HID.cpp
include .build/mega2560/arduino/HID.d

.build/mega2560/arduino/IPAddress.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/mega2560/arduino/IPAddress.d

.build/mega2560/arduino/main.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/main.cpp
include .build/mega2560/arduino/main.d

.build/mega2560/arduino/new.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/new.cpp
include .build/mega2560/arduino/new.d

.build/mega2560/arduino/Print.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Print.cpp
include .build/mega2560/arduino/Print.d

.build/mega2560/arduino/Stream.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Stream.cpp
include .build/mega2560/arduino/Stream.d

.build/mega2560/arduino/Tone.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Tone.cpp
include .build/mega2560/arduino/Tone.d

.build/mega2560/arduino/USBCore.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/USBCore.cpp
include .build/mega2560/arduino/USBCore.d

.build/mega2560/arduino/WMath.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WMath.cpp
include .build/mega2560/arduino/WMath.d

.build/mega2560/arduino/WString.o : /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WString.cpp
include .build/mega2560/arduino/WString.d



.build/mega2560/arduino/libarduino.a : .build/mega2560/arduino/avr-libc/malloc.o .build/mega2560/arduino/avr-libc/realloc.o .build/mega2560/arduino/WInterrupts.o .build/mega2560/arduino/wiring.o .build/mega2560/arduino/wiring_analog.o .build/mega2560/arduino/wiring_digital.o .build/mega2560/arduino/wiring_pulse.o .build/mega2560/arduino/wiring_shift.o .build/mega2560/arduino/CDC.o .build/mega2560/arduino/HardwareSerial.o .build/mega2560/arduino/HID.o .build/mega2560/arduino/IPAddress.o .build/mega2560/arduino/main.o .build/mega2560/arduino/new.o .build/mega2560/arduino/Print.o .build/mega2560/arduino/Stream.o .build/mega2560/arduino/Tone.o .build/mega2560/arduino/USBCore.o .build/mega2560/arduino/WMath.o .build/mega2560/arduino/WString.o
	@echo [92mLinking libarduino.a[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build/mega2560/src/sketch.o : .build/mega2560/src/sketch.cpp
	@echo [93msrc/sketch.cpp[0m
	@mkdir -p .build/mega2560/src
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -Ilib/OneWire -Ilib/RTClib -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/SD -Ilib/SD/utility -Ilib/DHT -Ilib/Wire -Ilib/Wire/utility -Ilib/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -fno-exceptions -iquote src  -o $@ -c .build/mega2560/src/sketch.cpp
include .build/mega2560/src/sketch.d







.build/mega2560/firmware.elf : .build/mega2560/src/sketch.o .build/mega2560/OneWire/libOneWire.a .build/mega2560/RTClib/libRTClib.a .build/mega2560/EEPROMEx/libEEPROMEx.a .build/mega2560/SD/libSD.a .build/mega2560/DHT/libDHT.a .build/mega2560/Wire/libWire.a .build/mega2560/SPI/libSPI.a .build/mega2560/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/mega2560/firmware.hex : .build/mega2560/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/mega2560/src/dependencies.d .build/mega2560/arduino/dependencies.d .build/mega2560/OneWire/dependencies.d .build/mega2560/Wire/dependencies.d .build/mega2560/RTClib/dependencies.d .build/mega2560/EEPROMEx/dependencies.d .build/mega2560/SPI/dependencies.d .build/mega2560/SD/dependencies.d .build/mega2560/DHT/dependencies.d

all : .build/mega2560/firmware.hex
	@true

