







	



.build/mega2560/SD/File.d : lib/SD/File.cpp
	@mkdir -p .build/mega2560/SD
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/OneWire -Ilib/RTClib -Ilib/SD -Ilib/SD/utility -Ilib/Wire -Ilib/Wire/utility  -MM $^ > $@
	
	@printf ".build/mega2560/SD/File.d .build/mega2560/SD/" | cat - $@ > $@~ && mv $@~ $@

.build/mega2560/SD/SD.d : lib/SD/SD.cpp
	@mkdir -p .build/mega2560/SD
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/OneWire -Ilib/RTClib -Ilib/SD -Ilib/SD/utility -Ilib/Wire -Ilib/Wire/utility  -MM $^ > $@
	
	@printf ".build/mega2560/SD/SD.d .build/mega2560/SD/" | cat - $@ > $@~ && mv $@~ $@

.build/mega2560/SD/utility/Sd2Card.d : lib/SD/utility/Sd2Card.cpp
	@mkdir -p .build/mega2560/SD/utility
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/OneWire -Ilib/RTClib -Ilib/SD -Ilib/SD/utility -Ilib/Wire -Ilib/Wire/utility  -MM $^ > $@
	
	@printf ".build/mega2560/SD/utility/Sd2Card.d .build/mega2560/SD/utility/" | cat - $@ > $@~ && mv $@~ $@

.build/mega2560/SD/utility/SdFile.d : lib/SD/utility/SdFile.cpp
	@mkdir -p .build/mega2560/SD/utility
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/OneWire -Ilib/RTClib -Ilib/SD -Ilib/SD/utility -Ilib/Wire -Ilib/Wire/utility  -MM $^ > $@
	
	@printf ".build/mega2560/SD/utility/SdFile.d .build/mega2560/SD/utility/" | cat - $@ > $@~ && mv $@~ $@

.build/mega2560/SD/utility/SdVolume.d : lib/SD/utility/SdVolume.cpp
	@mkdir -p .build/mega2560/SD/utility
	@/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/mega -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/avr-libc -Ilib/EEPROMEx -Ilib/EEPROMEx/Examples -Ilib/EEPROMEx/Examples/EEPROMEx -Ilib/EEPROMEx/Examples/EEPROMVar -Ilib/OneWire -Ilib/RTClib -Ilib/SD -Ilib/SD/utility -Ilib/Wire -Ilib/Wire/utility  -MM $^ > $@
	
	@printf ".build/mega2560/SD/utility/SdVolume.d .build/mega2560/SD/utility/" | cat - $@ > $@~ && mv $@~ $@



.build/mega2560/SD/dependencies.d : .build/mega2560/SD/File.d .build/mega2560/SD/SD.d .build/mega2560/SD/utility/Sd2Card.d .build/mega2560/SD/utility/SdFile.d .build/mega2560/SD/utility/SdVolume.d
	@echo [96mScanning dependencies of SD[0m
	@mkdir -p .build/mega2560/SD
	@cat $^ > $@;

all : .build/mega2560/SD/dependencies.d
	@true

